Repository marc0tjevp/Avans-NoSQL, pull requests merged in 2018-11, with the labels that each got.

#10 Setup express
  config/config.json
  config/swagger.config.json
  controller/auth.controller.js
  model/response/api.response.js
  model/response/notfound.response.js
  model/schema/user.schema.js
  package-lock.json
  package.json
  routes/auth.routes.js
  server.js
Labels: setup

#11 Initial models
  model/schema/comment.schema.js
  model/schema/thread.schema.js
  model/schema/user.schema.js
Labels: feature

#12 Feature endpoints
  controller/comment.controller.js
  controller/friend.controller.js
  controller/thread.controller.js
  controller/user.controller.js
  routes/comment.routes.js
  routes/friend.routes.js
  routes/thread.routes.js
  routes/user.routes.js
  server.js
Labels: feature

#23 Updated friends controller, now uses callback data
  controller/friend.controller.js
  neodb/neodbhelper.js
Labels: controller

#29 Version 1
  README.md
  config/authentication.config.js
  config/config.json
  config/swagger.config.json
  controller/auth.controller.js
  controller/comment.controller.js
  controller/friend.controller.js
  controller/thread.controller.js
  controller/user.controller.js
  model/response/api.response.js
  model/response/notfound.response.js
  model/schema/comment.schema.js
  model/schema/thread.schema.js
  model/schema/user.schema.js
  neodb/neodbhelper.js
  package-lock.json
  package.json
  routes/comment.routes.js
  routes/friend.routes.js
  routes/thread.routes.js
  routes/user.routes.js
  server.js
  test/comments.test.js
  test/friends.test.js
  test/test_helper.js
  test/thread.test.js
  test/users.test.js
Labels: yeet
